# Generated by Django 4.1.1 on 2022-09-22 01:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='../static/assets/images/NO-IMAGE.png', upload_to='photos/store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('month', models.IntegerField(default=9)),
                ('total', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.TextField(blank=True)),
                ('amount', models.IntegerField(default=1)),
                ('collection', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2022, 9, 21, 20, 43, 45, 89723))),
                ('carrier', models.CharField(choices=[('NA', 'NA'), ('Envia', 'Envia'), ('InterRapidisimo', 'InterRapidisimo'), ('Servientrega', 'Servientrega'), ('Domiclio', 'Domicilio')], default='NA', max_length=50)),
                ('guide', models.CharField(max_length=50)),
                ('freight', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('CANCELLED', 'Cancelado'), ('COMPLETE', 'Completado')], default='NEW', max_length=50)),
                ('delivery_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
