# Generated by Django 4.1.1 on 2022-09-24 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 19, 40, 40, 122784)),
        ),
    ]
