# Generated by Django 4.1.1 on 2022-09-24 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_customer_id_sale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 19, 46, 41, 931251)),
        ),
        migrations.AlterField(
            model_name='spent',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
