# Generated by Django 4.1.1 on 2022-09-27 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sale_date_alter_spent_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spent',
            name='month',
        ),
        migrations.RemoveField(
            model_name='spent',
            name='year',
        ),
        migrations.AddField(
            model_name='spent',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 10, 41, 3, 767619)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 10, 41, 3, 775621)),
        ),
    ]
